as yet unclassified
style
	^'
	.hdr { font-size: 18pt; font-weight: 700; color: #404080; padding: 10px 10px 20px 10px; }
	
	.prefs { padding: 10px; margin-bottom: 20px; margin-left: 10px; border: 1px solid #404080; width: 600px; }
	
	.logregform { padding: 10px; }
	
	.autherror { padding: 20px 10px 20px 10px; color: darkred; }
	
	.loginform { padding: 10px; }
	
	.loggedin { padding: 10px }
	
	.regsubmitfailed { padding: 20px 10px 20px 10px; color: darkred; }
	
	'